spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_recipe_prod
    username: spring_recipe_prod_user
    password: cute@ammu04
    platform: mysql

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true